package co.vividhata.accessibility_api.model;

public enum IssueType {
    ALT_TEXT_MISSING,
    CAPTIONS_FOR_VIDEO_AUDIO_MISSING,
    SEMANTIC_HTML_MISSING,
    CONTENT_MEANINGFUL_SEQUENCE_VIOLATION,
    NO_SINGLE_SENSORY_CHARACTERISTIC,
    LINE_HEIGHT_SPACING_VIOLATION,
    NOT_JUST_COLOR,
    TEXT_CONTRAST_VIOLATION,
    TEXT_RESIZE_VIOLATION, 
    KEYBOARD_OPERABLE,
    NO_KEYBOARD_TRAPS,
    TIME_LIMITS,
    CLEAR_PAGE_TITLES,
    FOCUS_ORDER_LOGICAL,
    DESCRIPTIVE_LINK_TEXT,
    ARIA_ROLE_MISSING_OR_INVALID, COMPONENTS_NOT_CONSISTENT, LANGUAGE_NOT_DEFINED, NO_DRAG_DROP_ALTERNATIVE, ERROR_SUGGESTION_NOT_PROVIDED, HELP_NOT_AVAILABLE, MULTIPLE_WAYS_TO_NAVIGATE
}
