package co.vividhata.accessibility_api.model;

public enum IssueType {
    ALT_TEXT_MISSING,
    CAPTIONS_FOR_VIDEO_AUDIO_MISSING,
    SEMANTIC_HTML_MISSING,
    CONTENT_MEANINGFUL_SEQUENCE_VIOLATION,
    NO_SINGLE_SENSORY_CHARACTERISTIC,
    LINE_HEIGHT_SPACING_VIOLATION,
    NOT_JUST_COLOR,
    TEXT_CONTRAST_VIOLATION
}
